= Primary Productivity around Antarctic Peninsula
Arnaldo D`Amaral Pereira Granja Russo
:homepage: ciclotux.org
:numbered:
:toc:
:sectanchors:
:icons: font

== Introduction

Testing some upperscript and downscript F~v~/F~m~ and values 0.5, 0.6. Also
some citation goes here Holeton et al. (2005).

== Methods

Some texts referencing the methods, sampling and procedure.

== Results

Here comes my results

== Discussion

Testing characters Latin-1.
A Discussão vai aqui com um monte de textos e referências para quem é de ler.

== Conclusão

Seguem aqui as principais conclusões do trabalho.

== Agradecimentos

Agradecimentos

== Referências Bibliográficas
Holeton, C.L., N\'ed\'elec, F., Sanders, R., Brown, L., Moore, C.M., Stevens, D.P., Heywood, K.J., Statham, P.J., Lucas, C.H., 2005. Physiological state of phytoplankton communities in the Southwest Atlantic sector of the Southern Ocean, as measured by fast repetition rate fluorometry. Polar Biology 29, 44–52. doi:10.1007/s00300-005-0028-y

